- src/doc_builder/build_doc.py
- tests/test_build_doc.py
Currently numbers are stripped from anchor links.
This PR fixes this issue
cc: @stas00
> Support numbers in anchors

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
This fixes the issue with some parameters not being recognized because they are introduced with "Arguments:" (cf problem [here](https://github.com/huggingface/transformers/issues/14613#issuecomment-985538424)).
> Add Arguments: to the supported parameters introduction

- src/doc_builder/build_doc.py
- src/doc_builder/commands/convert_doc_file.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_build_doc.py
This PR adds the syntax to resolve [[open-in-colab]] in doc files to the proper svelte component.
It also introduces a few fixes used when converting some rst files.
> Add open-in-colab syntax and fixes to conversion

- setup.py
- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
- src/doc_builder/convert_to_notebook.py
- tests/test_autodoc.py
- tests/test_build_doc.py
- tests/test_convert_to_notebook.py
This PR adds the ability to convert doc pages to notebook auto-magically, as long as they have the `[[open-in-colab]]` marker: when building the documentation, a `notebook_dir` just has to be provided.
The generated notebooks look exactly like their doc page counterpart with a few exceptions:
- the code samples are parsed in proper code cells, and the doctest syntax is removed to separate inputs and outputs.
- the youtube svelte components are replaced by hidden cells displaying the videos
- all links are treated to point to the doc (links to an object in the package lie [`Trainer`] are of course properly resolved)
- LaTeX special syntax is changed to the usual $ $ 
- PT/TF content is split to generate one Mixed, one PyTorch-only and one TF-only notebook.
To test locally:
```
doc-builder …
```
> Convert doc page to notebooks

- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_md_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Companion pr to https://github.com/huggingface/moon-landing/pull/1641
Adds svelte imports for FrameworkSwitch svelte component
@sgugger when writing FrameWork specific text, you need to do 2 things:
1. Put `<FrameworkSwitch {fw} />` after title, can be before or after  `opne-in-colab`, see [example here](https://github.com/huggingface/doc-builder/blame/demo_fwswitch_colab/build/transformers/master/en/quicktour.mdx#L43-L53)
2. Write framework specific text/content using svelte if else statements, see [example here](https://github.com/huggingface/huggingface-course/blame/402565b43df4ecbd477136e16d35922ab41ad6c5/chapters/chapter2/section3.mdx#L9-L13)
3. Svelte if else condition supports [else-if](https://svelte.dev/tutorial/else-if-blocks), therefore, we are future-proof for flax additions
> Add framewotkswtich svelte

- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_md_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Reverts huggingface/doc-builder#49
My bad for not notifying about this. We should merge this #49 after https://github.com/huggingface/moon-landing/pull/1641
> Revert "Add framewotkswtich svelte"

- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
- src/doc_builder/convert_to_notebook.py
- src/doc_builder/utils.py
- tests/test_convert_to_notebook.py
This PR adds the ability to customize the first cell(s) of auto-generated notebooks. For transformers we want to install `transformers` and `datasets`  but for other packages we will want something different.
I took the approach of using a `_config.py` file (a bit like the old conf.py for Sphinx or the one used in pytest) that would look like this for Transformers (see [this PR](https://github.com/huggingface/transformers/pull/14718)):
```
INSTALL_CONTENT = """
! pip install transformers datasets
"""
notebook_first_cells = [{"type": "code", "content": INSTALL_CONTENT}]
```
And since we might add other customizable things in the future, I made the architecture to get that config as a Python module.
> Add custom first cell

- src/doc_builder/build_doc.py
This PR adds a check for the ToC, specifically that it contains all the doc-generated files. If it does not, the `doc-builder` will now error (like sphinx used to).
As a result this PR shouldn't be merged without its [counterpart](https://github.com/huggingface/transformers/pull/14755) on the Transformers side (which adds missing files in the ToC).
> Add a check for the ToC

- src/doc_builder/utils.py
As seen in Transformers earlier today, the doc building will fail if there is no config file in the doc folder, which shouldn't be the case since users are allowed to not want to customize their doc building.
> Don't error if package has no doc config

- src/doc_builder/commands/convert_doc_file.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_doc_file.py
- tests/test_convert_rst_to_mdx.py
This PR adds a command to convert all the docstrings in a python file to Markdown. It uses the already existing command `doc-builder convert`, which has a different behavior for rst files (convert them to MDX) and py files (convert all the docstrings inside that are written in rst).
You can test this in the Transformers repo by running:
```bash
doc-builder convert src/transformers/models/bert/modeling_bert.py
make style
```
(make style is to re-organize the content with the 119 char limit) and enjoy the diff!
> Add docstrings conversion to doc-builder convert

- src/doc_builder/commands/convert_doc_file.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_doc_file.py
- tests/test_convert_rst_to_mdx.py
This fixes a current bug where the parameters description is not properly parsed if a parameters as a note or a warning inside its description. The problem comes from the fact we remove indentation there, so this PR retains it so we don't leave the parameter block.
For regular rst files, the conversion remove all needless indentation later on, so this is safe to do.
> Fix parameters parsing when there is a note or warning inside

- src/doc_builder/autodoc.py
- src/doc_builder/convert_md_to_mdx.py
This PR fixes a little bit the conversion MD to MDX by removing the indent (that stays for all the arguments otherwise). It's all whitespace, so not sure it has a real impact on moon-landing, but it removes the diff I get when converting docstrings of the models from rst to MarkDown.
> Docstring MD to MDX conversion fixes

- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- tests/test_autodoc.py
This PR adds a few defensive checks to make sure the docstrings built do not cause any issue on moon-landing.
It needs some fixes on the Transformers side so do not merge yet :-)
> Add defensive checks to prevent moon-landing deployment issues

- src/doc_builder/commands/build.py
Dev build should not update _versions.yml file
Reusing this bool/flag https://github.com/huggingface/doc-builder/blob/0e9fffb822ef46edc5aa10c0f44baa6193e41732/src/doc_builder/commands/build.py#L29
We can add other agument like `if arg PR_number exists` wdyt
> Dev build should not update _versions.yml file

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Problem: some docstrings can produce multiple `parameters` blocks like[ RealmScorer here](https://github.com/huggingface/transformers/blob/22454ae492eca4bb749fa6d770dffc91d17dab87/src/transformers/models/realm/modeling_realm.py#L1222-L1226), which was producing something that looks like:
```
docstring
Args:
....
Parameters:
....
end
```
, which was causing the problem on the parsing side since only one param block is expected.
This PR solves this issue by combining multiple parameters blocks into one block if there are multiple parameter blocks.
```
Args:                                                Args:
....                                   --->           param1 --
Parameters:                                               param2 --
.... …
```
> Group parameter blocks into one

- src/doc_builder/autodoc.py
- tests/test_autodoc.py
Currently links with a code block like \[\`Accelerator\`\]\(https://huggingface.co/docs/accelerate/accelerator.html#accelerate.Accelerator\) are changed by `doc-builder` when it attemps to resolve the links to other parts of the docs (since it does not found the object in the doc of Transformers). This PR fixes that and adds a test.
> Fix real links with a code block

- src/doc_builder/utils.py
This makes sure the version is not added to `_versions.yml` if it's already there, to avoid duplicates (like in [this commit](https://github.com/huggingface/doc-build/commit/f3c1b81c9967d09cf0f1c56c80977aca2bb8ece0)).
> Only add version if it's not there already

- src/doc_builder/build_doc.py
- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_build_doc.py
- tests/test_convert_md_to_mdx.py
As we discussed, adding aws studio lab option to notebooks dropdown.
Old syntax:
```
<ColabDropdown hydrate-props={{
classNames: "absolute z-10 right-0 top-0",
options:[
{label: "Mixed", value: "https://colab.research.google.com/github/huggingface/notebooks/blob/master/transformers_doc/training.ipynb"},
{label: "PyTorch", value: "https://colab.research.google.com/github/huggingface/notebooks/blob/master/transformers_doc/pytorch/training.ipynb"},
{label: "TensorFlow", value: "https://colab.research.google.com/github/huggingface/notebooks/blob/master/transformers_doc/tensorflow/training.ipynb"},
]}} />
```
New syntax:
```
<DocNotebookDropdown hydrate-props={{
classNames: "absolute z-10 right-0 top-0",
options:[
{label: "Mixed", value: …
```
> Repalce `ColabDropdown` with `DocNotebookDropdown`

- src/doc_builder/autodoc.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_autodoc.py
- tests/test_convert_rst_to_mdx.py
Unlike transformers docs, datasets docs has a lot of using `raises` section in docstring. Therefore, this PR implements catching raises sections in docstrings
> Catch raises section in docstring

- setup.py
- src/doc_builder/autodoc.py
- src/doc_builder/utils.py
- tests/test_utils.py
Example Input:
```
Description
More description
Parameters
----------
columns : list, optional
List of column to be converted. If None, use all columns.
safe : bool, default True
Check for overflows or other unsafe conversions.
Raises
------
KeyError
If any of the passed columns name are not existing.
ValueError
Returns
-------
Table
New table without the columns.
Examples
--------
>>> import pandas as pd
>>> import pyarrow as pa
>>> df = pd.DataFrame({
...     'int': [1, 2],
...     'str': ['a', 'b']
... })
>>> pa.Table.from_pandas(df)
<pyarrow.lib.Table object at 0x7f05d1fb1b40>
```
Example Output:
```
Description
More description
Args:
columns (`list`, `optional`): List of column to be converted. If None, use all columns.
safe (`bool`, defults to `True`): Check for overflows or other …
```
> Convert numpy doc style to groups doc style

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Catch `Attributes` keyword in `_re_args` because of [this](https://github.com/huggingface/datasets/blob/21bfd0d3f5ff3fbfd691600e2c7071a167816cdf/src/datasets/info.py#L95-L101)
> Add `Attributes` to `_re_args`

- src/doc_builder/autodoc.py
- tests/test_autodoc.py
`dataclass` decorator auto generates docs for a class if the class doesn't have a doc. The generated doc is redundant with the class signature. Therefore, we don't want that. See [the test example](https://github.com/huggingface/doc-builder/pull/93/commits/77085f8cdff8c9daba8817d6d4d03e89e95735df) for more info
> Handle data class auto generated doc

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
In datastes docs, there are docstrings with return type but without return descriptions.
```
def cast_column(self, column: str, feature: FeatureType) -> "IterableDataset":
"""Cast column to feature for decoding.
Args:
column (:obj:`str`): Column name.
feature (:class:`Feature`): Target feature 2.
Returns:
:class:`IterableDataset`
"""
```
`split_return_line` function was not handling this case properly.
> Return type without return description

- src/doc_builder/autodoc.py
- tests/test_autodoc.py
Fixes https://github.com/huggingface/doc-builder/pull/94#issuecomment-1042383743
@sgugger please let me know if there was a specific reason why this espacing was here initially
cc: @Pierrci
> Rm `name.replace("_", "\_")`

- kit/svelte.config.js
- src/doc_builder/commands/build.py
Add `library_name` to env args so that other libraries can be used as well such as `datasets`
> Add library_name to env args

- src/doc_builder/autodoc.py
When `obj.__doc__` is empty, no mdx section for that doc gets generated.
https://github.com/huggingface/doc-builder/pull/96 fixes the problem by generating the signature str/svelte for that doc even if `obj.__doc__` is empty.
I realize that #95 was overcomplicating things. Please let me know if the problem is clear 🙂
> Fix document_object when objdoc is empty

- src/doc_builder/commands/build.py
This fixes the --help of the command `doc-builder build` for the `--version` argument.
Fixes #105
> Fix documentation of --version in doc-builder build

- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_to_notebook.py
This PR cleans up the doctest artifacts that may appear in examples:
- flags to ignore outputs or skip
- a framework split variation since we can't use the regular one and it doesn't look like #63 is going to be merged any time soon.
> Clean up doctest artifacts

- src/doc_builder/build_doc.py
- tests/test_build_doc.py
This removes the hard-coded "transformers" to support other libraries (like datasets)
> Support any package name in notebooks widget

- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- src/doc_builder/utils.py
This PR cleans up all docstrings to make them consistent with the way we document things in Markdown.
> Clean up docstrings

- kit/postbuild.sh
Do not output CSS file in sveltekit build to avoid problem mentioned [here](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1646069793888439?thread_ts=1646055958.293249&cid=C02GLJ5S0E9).
There is still main body shifting to the left glitch, which is caused by [SubSideMenu and its breakpoints loading](https://github.com/huggingface/moon-landing/blob/4a16818bf77260ad9f3d23d530c990b859fac464/server/views/pages/DocPage/DocBuilderPage.svelte#L69). Will handle that problem in a separate moon-landing PR.
Rather than reverting the entire CSS addition as in [here](https://github.com/huggingface/doc-builder/pull/113), I'd like to keep it for dev purposes.
In the video below, I load the bert page 3 times for demo:
https://user-images.githubusercontent.com/11827707/156076438-d61b3aa3-becb-4580-b0d …
> Make generated CSS empty

- kit/preprocess.js
- kit/src/lib/CodeBlockFw.svelte
- kit/src/lib/Docstring.svelte
- kit/src/lib/FrameworkSwitch.svelte
- kit/src/lib/stores.ts
- kit/src/lib/types.ts
Generalizing CodeBlockFw.svelte components.
Before, CodeBlockFw.svelte only supported `Pytorch/Tensorflow` tabs. Example [url](https://moon-preprod.huggingface.co/docs/datasets/quickstart)
With this PR, it will also support `String API/ReadInstruction` tabs. Example [url](https://moon-preprod.huggingface.co/docs/datasets/master/en/loading#slice-splits)
> Changes for datasets new frontend

- src/doc_builder/build_doc.py
This PR adds support to automatically generate an `objects.inv` file in each doc that contains the references to all the anchors of the objects in the doc. This is then used by other projects that use Sphinx to generate their documentation to automatically link to our documentation, see [here](https://sphobjinv.readthedocs.io/en/latest/syntax.html) for more details.
Fixes #81
> Generate objects.inv file

- src/doc_builder/commands/build.py
This PR removes the `objects.inv` out of the build dir before running `npm build`.
> Move objects.inv out of the way during npm build

- src/doc_builder/commands/build.py
- src/doc_builder/utils.py
We hardcode `"master"` for the version in development but we should use the repo default branch (for instance `"main"`). This PR addresses that.
> Respect repo default branch

- .github/workflows/accelerate_doc.yml
This PR adds a new GitHub action that builds the doc of Accelerate on each PR. This makes a nice integration test that stays short.
> Add integration test for doc building

- src/doc_builder/convert_rst_to_mdx.py
If a return statement takes several lines (like models in the Transformers library) the `return_type` is replaced by None at the second line of that return statement. This PR fixes that.
> Don't replace return type

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
This PR fixes a wrong indent done in `remove_indent` which I believe is the cause for the documentaiton of [`from_pretrained`](https://huggingface.co/docs/transformers/master/en/main_classes/model#transformers.PreTrainedModel.from_pretrained) in Transformers to be truncated.
The crux of the issue is that a docstring like this:
```
Lala
Loulou
- This is a list.
This item is long.
- This is the second item.
- This list is nested
- With two items.
Now we are at the nested level
```
is currently reindented like this:
```
Lala
Loulou
- This is a list.
This item is long.
- This is the second item.
- This list is nested
- With two items.
Now we are at the nested level
```
and so the list of parameters is interrupted before its end. This PR fixes it and adds a new test.
> Fix indentation in some nested list cases

- MANIFEST.in
- setup.py
- src/doc_builder/utils.py
The kit subfolder can't be packaged with `doc-builder` as it makes a tar file that is too heavy (105MB) and PyPi refuses it. This PR removes it from the package (deletion of the manifest file) and introduces a mechanism for cloning and caching the repo to access the kit subfolder.
> Git clone for kit

- .gitignore
- MANIFEST.in
- setup.py
This PR prepares the packaging of `doc-builder` by:
- updating the MANIFEST to include the kit src subfolder but no other subfolders.
- changing the name to `hf-doc-builder` (as `doc-builder` is too close to a name chosen on Pypi)
To avoid changing the workflow of people, the CLI tool and the module are still going to be named `doc-builder`, but the package will be installable from Pypi via `pip install hf-doc-builder`.
> Preparation for packaging

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
This PR changes the doc building jobs to try to rebase and push again if the first push fails.
> Retry for failed pushes

- src/doc_builder/autodoc.py
In a namespace module (like `optimum`), submodules won't directly appear as attributes. You need to import them at least one explicitly before they do. This PR does that.
> Optimum fixes

- .github/workflows/build_main_documentation.yml
- kit/README.md
- kit/svelte.config.js
- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
- src/doc_builder/commands/preview.py
- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- src/doc_builder/convert_to_notebook.py
- src/doc_builder/utils.py
- tests/test_autodoc.py
- tests/test_build_doc.py
- tests/test_convert_rst_to_mdx.py
- tests/test_convert_to_notebook.py
This PR changes the default branch to "main" everywhere master is used, in particular for the notebook building job (for the rest it's the default in internal functions, which is trumped by the version set when building the doc anyway).
It also fixes a few tests due to the recent reorganization in Transformers splitting `file_utils` in several submodules.
> Switch default branch to main and fix tests

- src/doc_builder/commands/build.py
This PR adds a check on the version argument for non-Python modules. We need this merged to `main` to test the CI template for the course
> Enable version to be set for non-modules

- src/doc_builder/commands/style.py
- src/doc_builder/style_doc.py
This PR introduces two small fixes to make the doc-builder style command work on Transformers (it needs to access the doc-builder config as we have some specific patterns to deal with in the generic docstrings)
> Fixes for the doc-builder style command

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/build.py
This PR adds logic to skip the `pip install .[dev]` step in the doc building templates if the `--not_python_module` argument is provided. This should solve the failing build for the course [here](https://github.com/huggingface/course/runs/5690210360?check_suite_focus=true)
> Skip package install if --not_python_module is provided

- src/doc_builder/commands/build.py
This PR removes the notebook build when the job is called with a released version and not the main/master version: the doc building job always pushes notebooks to the main branch of the notebooks repo, so it shouldn't be updated for a released version.
> Disable notebook building for non-main builds

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
This PR reverts the revert in #161 to properly set the shell to `bash` when we run the `Setup environment` step. As far as I can tell, `ubuntu-latest` actually runs `dash` by default, so it couldn't parse the double `[[` brackets that we use for substring matching, e.g. in https://github.com/huggingface/doc-builder/issues/160 we encounter the following error in the CI:
```
/__w/_temp/75bf1d4b-4452-4c1d-8927-838e5094620a.sh: 7: [[: not found
```
Setting `shell: bash` in the CI step resolves the issue and here are two successful builds of the docs on `datasets` and `course` based on this branch:
* https://github.com/huggingface/datasets/runs/5718880095?check_suite_focus=true
* https://github.com/huggingface/course/runs/5719043810?check_suite_focus=true (the add doc comment step fails, but …
> Skip package installation if `--not_python_module` provided

- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- tests/test_autodoc.py
There is a problem in the way anchors are generated for methods of classes that are inherited from a superclass. The problem was first reported in [this PR](https://github.com/huggingface/datasets/pull/3999) but it happens more broadly when you have an object (let's say `BertTokenizer`) and a method (let's say the `__call__` magic method) that you are asking in the documentation, but that method's documentation is actually written in the superclass (in our example `PreTrainedTokenizerBase`).
Currently, doc-builder will create the documentation of this method under the anchor `PreTrainedTokenizerBase.__call__` which has two problems:
- if we were in a page with two different tokenizers documenting that method, we would get the same anchor twice
- more annoying is that this method can never …
> Support anchor names for inherited methods

- src/doc_builder/autodoc.py
#163 introduced a bug that makes the build of Transformers fail. This PR fixes it by adding an extra check to avoid introducing `None` anchors.
> Fix doc-building on Transformers

- README.md
The `build` keyword is missing
> Fix `build` command in README.md

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
This PR adds multilingual support for the CI templates via a new `languages` argument. Thanks to a tip from @sgugger, the current logic is _opt-in_ which means that multilingual docs are only created if the `languages` argument is provided and the source docs are structured as follows:
```
doc_folder
├── en
│   ├── _toctree.yml
...
└── es
├── _toctree.yml
...
```
An [example](https://github.com/huggingface/doc-build-dev/tree/main/course/pr_39) showing a successful build for the course can be found in this PR: https://github.com/huggingface/course/pull/39
Similarly, an example showing that the current implementation works for monolingual docs can be found here: https://github.com/huggingface/datasets/pull/4055
> Add multilingual support for CI templates

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
As discussed in https://github.com/huggingface/moon-landing/pull/2499 this PR enables the docs directory on hf.co to be configurable via a `hub_docs_dir` argument. By default, the docs URL will be 
```
https://moon-ci-docs.huggingface.co/docs/{package_name}/pr_{pr_number}
```
but for the course we can configure this to be 
```
https://moon-ci-docs.huggingface.co/course/{package_name}/pr_{pr_number}
```
A test run with the course CI can be found here: https://github.com/huggingface/course/pull/68
> Enable Hub docs directory to be configurable

- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
- tests/test_build_doc.py
This PR makes sure that when we set a language argument, we build the notebook in subfolders of notebook_dir (one per language). This will change the current structure (e.g. notebooks will now be pushed to transformers_doc/en instead of just transformers_doc) but makes things support multilingual doc, so I think it's okay.
> Enable support for notebooks in multiple languages

- kit/src/app.css
- kit/src/lib/Docstring.svelte
- kit/svelte.config.js
One thing I really like about rust docs is that hashlinks are highlited in frontend.
For example, [this one](https://docs.rs/rayon/latest/rayon/iter/trait.ParallelIterator.html#method.cloned)
This PR, implements a similar behaviour for doc-builder
| lightmode | darkmode |
|-----------|----------|
| <img width="738" alt="Screenshot 2022-04-06 at 12 05 07" src="https://user-images.githubusercontent.com/11827707/161953622-4788693e-47f0-43b2-a2cc-c83d43951e30.png">         | <img width="526" alt="Screenshot 2022-04-06 at 12 08 26" src="https://user-images.githubusercontent.com/11827707/161953630-31c10252-147e-418b-a10e-da8d026b0a68.png">       |
cc: @sgugger @LysandreJik 
TODO: add moon-landing tailwind classes
> [frontend] Highlight hashlinks

- .github/workflows/build_main_documentation.yml
This PR fixes the template job that builds the documentation, to make sure we only try to push notebooks when they have been created: a doc job for a specific version does not create them, which results in an error.
> Fix notebook push in template

- README.md
- src/doc_builder/build_doc.py
- src/doc_builder/convert_md_to_mdx.py
- tests/data/convert_literalinclude_dummy.py
- tests/data/convert_literalinclude_dummy.txt
- tests/test_convert_md_to_mdx.py
I'm in the process of migrating [tokenizers](https://github.com/huggingface/tokenizers) & [inference-api ](https://api-inference.huggingface.co/docs/python/html/index.html) repos to new frontend.
One of the missing capabilities needed is `literalinclude start-after end-before` (example [here](https://github.com/huggingface/tokenizers/blob/main/docs/source/pipeline.rst#id24)), as mentioned in #173
The syntax I'm proposing is html-like tags `<literalinclude>...</literalinclude>`, which will hold python dict str between them specifying options. Wdyt?
Example:
```
<literalinclude>
{'path': './data/convert_literalinclude_dummy.txt', # relative path
'language': 'python', # defaults to '' (empty str)
'start-after': 'START python_import',
'end-before': 'END python_import',
'dedent': 7 # defaults …
```
> Literalinclude start-after end-before

- src/doc_builder/build_doc.py
- tests/test_build_doc.py
Reverts huggingface/doc-builder#184
Reverting the PR as it breaks a lot of things across repos with no easy fix (the failures are reported at the first file, not all together). This needs to be more carefully integrated.
> Revert "Raise exception when non-unique headings"

- kit/preprocess.js
- kit/src/lib/Docstring.svelte
- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
2 features are turned off for tokenizers doc builds:
1. Tokenizers python docs will NOT have `source` btn 
2.`doc-builder preview` cmd hot reloading will NOT track docstring changes in tokenizers python bindings files.
The reason why these 2 features are turned off are: tokenizers python bindings objs:
1.  do not work with `inspect.getsourcelines` & `inspect.getfile`
2. do not have `__module__` attribute 
an error gets thrown:
```
<function descriptor> does not have XYZ
```
taking the easier/simpler route of excluding those 2 features (imo, since they are not essential, especiialy the second one) rather than trying to find a solution [because](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1649327824975459?thread_ts=1649326613.932349&cid=C02GLJ5S0E9)
>  The tokenizers doc is (sadly) …
> Changes needed for tokenizers

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Needed for https://github.com/huggingface/tokenizers/pull/980
See [here](https://github.com/huggingface/tokenizers/blob/95b5d066d5b90582ceccb76b84b7d41351532e82/.github/workflows/build_pr_documentation.yml#L18-L19)
Adding 2 new [inputs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow) to doc build gh workflows:
1. `package_path`: because tokenizers python package is not in its git root folder, but in `tokenizers/bindings/python`
2. `install_rust`: installing rust is needed to install tokenizers from source
For install `install_rust`, I wanted to re-use [additional_args](https://github.com/huggingface/doc-builder/blob/main/.github/workflows/build_pr_documentation.yml#L18) but `additional_args` gets passed to …
> GH workflow changes for tokenizers

- kit/preprocess.js
There was a bug where empty frameworkcontent was being shown (see attached img). The expected behaviours is that: empty framework content should not be displayed
> Fix fw content bug

- kit/postbuild.sh
Closes #198
Previously, `sed` was failing with like [here](https://github.com/huggingface/doc-builder/runs/6158261692?check_suite_focus=true#step:7:28):
```
sed: can't read s/rel="stylesheet"/rel="modulepreload"/g: No such file or directory
```
> Fix `postbuild.sh`

- src/doc_builder/commands/build.py
There was a bug in `version_tag` was decalred
followup to https://github.com/huggingface/doc-builder/pull/200
> Fix version_tag

- src/doc_builder/autodoc.py
- tests/test_autodoc.py
This takes care of the problem highlighted in [this issue](https://github.com/huggingface/transformers/issues/16904). Objects defined in an `__init__.py` have a wrong source link returned.
> Fix source link for objects defined in an __init__

- src/doc_builder/commands/build.py
As suggested [here](https://github.com/huggingface/doc-builder/pull/203#discussion_r859752858)
apologies for causing bunch of issues because of #200 😊
Tested both on transformers & datasets, the source urls are working correctly:
https://huggingface.co/docs/transformers/main/en/model_doc/bert#transformers.BertConfig
https://huggingface.co/docs/datasets/master/en/package_reference/main_classes#datasets.DatasetInfo.from_directory
> Rm unneded if condition for `version_tag`

- src/doc_builder/style_doc.py
Currently `doc-builder style` will return an error if a file has an empty docstring. This PR fixes that.
> Don't error in style_doc for empty docstrings

- src/doc_builder/style_doc.py
For example formatting, we need to use `...` for any line that starts with a closing parenthesis/bracket. This PR fixes this (before it was required the whole line be just a closing parenthesis/bracket).
Fixes #206
You can see the changes it makes in Transformers in [this PR](https://github.com/huggingface/transformers/pull/17015)
> Fix example formatting

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Context: migrating hf.co/docs/hub to using doc-builder
The repo/package name is [hub-docs](https://github.com/huggingface/hub-docs), but we want to output in [hub](https://github.com/huggingface/doc-build-dev/tree/main/hub)
> Optional `package_name` attribute for gh workflows

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- src/doc_builder/build_doc.py
1. Currently, we assume "section titles" (highlighted red in the attached img) to not be pages themselves (i.e. have `local` attribute in their yml).
This PR makes it possible for  "section titles" to be pages too. (Context: needed for new hub docs, see more [here](https://www.notion.so/ec395476acf846879f57ee033fcee963) & [here](https://huggingface.slack.com/archives/C03969VA7NK))
2. The repo/package name is [hub-docs](https://github.com/huggingface/hub-docs), but we want to output in [hub](https://github.com/huggingface/doc-build-dev/tree/main/hub)
> Changes needed for building hub-docs

- kit/src/routes/__layout.svelte
Accurate widhts (i.e. same width as used in hf.co/docs) for side menu & sub-side menu when using preview cmd
> Accurate side menu width for preview

- kit/postbuild.sh
Replace hash in filenames of build artifcats with substring `hf-doc-builder` so that git diff can be smaller since different hashes create new files that dont share git history.
[See more here
](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1653058266060879?thread_ts=1652694685.797019&cid=C02GLJ5S0E9)
example: `assets/paths-4b3c6e7e.js` -> `assets/paths-hf-doc-builder.js`
ideally, we use [output.assetFileNames](https://rollupjs.org/guide/en/#outputassetfilenames) in [vite build config](https://vitejs.dev/config/#build-rollupoptions) used [here in doc-builder](https://github.com/huggingface/doc-builder/blob/2ee7c63f4945b63762ffa61a52c1d227a7ccb415/kit/svelte.config.js#L38-L42).
However, svelte-kit does not allow it; see https://github.com/sveltejs/kit/issues/1410
Therefore, using a …
> Rm `[hash]` from doc-build artifcats

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- setup.py
- src/doc_builder/commands/commit.py
- src/doc_builder/commands/doc_builder_cli.py
- src/doc_builder/commands/push.py
Problem: read more [here](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1648134906365829)
> Cloning it in a GitHub Action workflow takes about 4 minutes, even with a --depth 1
Solution: as suggested by ~@LysandreJik~ @julien-c (edit by @LysandreJik), use Github GraphQL [createcommitonbranch mutation](https://github.blog/changelog/2021-09-13-a-simpler-api-for-authoring-commits/). And this PR does that
I've tested it on accelerate [here](https://github.com/huggingface/accelerate/pull/372/files) and it is [working here](https://github.com/huggingface/accelerate/runs/6498426135?check_suite_focus=true)
btw, can confirm that pushing with GraphQL is way fater since we do not need to clone doc-build-dev (which is roughly 30GB in size atm)
todo (note for myself):
> Commit files to `doc-build(-dev)?` using Github GraphQL

- src/doc_builder/commands/build.py
Reverts huggingface/doc-builder#230
> Revert "files/folders cannot have a name that starts with `__` since it is a reserved Sveltekit keyword"

- kit/preprocess.js
- kit/src/lib/Added.svelte
- kit/src/lib/Changed.svelte
- kit/src/lib/Deprecated.svelte
- src/doc_builder/convert_md_to_mdx.py
https://github.com/huggingface/doc-builder/pull/233 was not working as expected because I did not add regex to escape `<Added|Changed|Derpecated>` inside docstrings & this PR solves that
related to https://github.com/huggingface/datasets/pull/4429
> Escape changed derivates inside docstring

- src/doc_builder/autodoc.py
When resolving links, the doc-builder adds parenthesis for every object that is not a class. But properties shouldn't get a pair. This PR fixes that.
> Don't add () for properties

- src/doc_builder/commands/doc_builder_cli.py
- src/doc_builder/commands/notebook_to_mdx.py
This PR adds a command to convert a notebook to an mdx file, making it easier to draft a new tutorial as a notebook and then converting it.
> Add notebook_to_mdx command

- README.md
This PR documents how to document an enum-like class and not have the attributes render as `Parameters:` in the documentation.
> Document how attributes should be included

- src/doc_builder/autodoc.py
When building the documentation for namespace packages such as Optimum subpackages (Graphcore/Habana/Intel), the package name is `optimum.{subpackage_name}`. For class or methods that are not imported in the root `__init__.py` of the subpackage, the command `[[autodoc]] path_to_my_class_or_method` will fail [here](https://github.com/huggingface/doc-builder/blob/77bf777999bb71f5f3c018f4d3b54b1616b544a2/src/doc_builder/autodoc.py#L83) because:
- no short name is available
- it will try to access the attribute `XXX` of the module `optimum.XXX`
You can find an example of such failure [here](https://github.com/huggingface/optimum-habana/runs/7620419218?check_suite_focus=true).
This PR proposes to initialize the value of the index `idx` at `module.__name__.count(".")` to take into account the …
> Adapt index for namespace packages in autodoc.get_shortest_path

- src/doc_builder/style_doc.py
- tests/test_style_doc.py
There is currently a bug in the doc styler when there is an empty line after the parameter introduction:
```py
"""
Function description
Params:
x (`int`): This is x.
y (`float`): this is y.
"""
```
This will reformat all arguments on the same line after, an issue we have seen recently in Transformers with a generate doc PR. It will give:
```py
"""
Function description
Params:
x (`int`): This is x. y (`float`): this is y.
"""
```
This PR fixes the bug and removes the extra empty lines so reformats the above as:
```py
"""
Function description
Params:
x (`int`): This is x.
y (`float`): this is y.
"""
```
Note: after being merged, we will need a release and a quick update to Transformers as this changes 16 files currently.
> Fix bug in styler when line after Parameter block is empty

- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/push.py
Closes https://github.com/huggingface/doc-builder/issues/272
graphQL should commit deletions too:
tested by: [here](https://github.com/huggingface/hub-docs/pull/286/commits/68705ee3f47ddd3241aacf5f642203198f37b011) & [here](https://github.com/huggingface/doc-build-dev/commit/1c325b047e781e40d1f660311b544d593b66a774)
> `create_commit` cmd support deletions

- src/doc_builder/commands/push.py
Closes https://github.com/huggingface/doc-builder/issues/275
> GraphQL commit deletion

- src/doc_builder/commands/push.py
Closes https://github.com/huggingface/doc-builder/issues/292
What was going on:
1. [This commit](https://github.com/huggingface/doc-build/commit/a1712d853c879966994cb4b476e07cfbebd34731) increments the version as transformers v.4.22 in _versions.yml
2. But afterwards immediately, [this commit](https://github.com/huggingface/doc-build/commit/9c940d6baa4f317db12f18fc4492621c6f339da9) removes v4.22 _versions.yml when transformers.__version__ changes back to dev mode
The explanation is that step2 had "old" _version.yml file before step1 finished committing the "new" _versions.yml
As a solution, we will not commit changes to _versions.yml when the branch is `main`
> Fix _versions.yml merge collisions

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Resolves #300. Any thoughts on `"required: true"` vs `"required: false"` would be nice here :).
> Add repo_owner input to build workflows

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
> :bug: use proper package_name in doc-builder build cmd

- src/doc_builder/autodoc.py
- tests/test_autodoc.py
Resolve function/method parameter links in MD/MDX files.
This is the syntax for the parameter links:
```
[`package.module.function#parameter`]
``` 
And this is what's left after the resolution step:
```
[parameter](url_with_function#package.module.function.parameter)
```
> Resolve params in text

- src/doc_builder/style_doc.py
- tests/test_style_doc.py
As the title says, handles the case where there is no empty line before the argument block, which was causing weird patterns to pop up in other libraries (like `transformers`).
For instance, 
```
Some description
Args:
- foo
```
was being converted to
```
Args:
Some description
- foo
```
This was because the paragraph was not seen as completed (no blank line), and the `Args:` line was appended as soon as it was seen. After this PR, the example above is converted to 
```
Some description
Args:
- foo
```
i.e. an empty line before `Args:` is added when it is missing.
> Handle the case where there is no empty line before the argument block

- .github/workflows/quality.yml
- src/doc_builder/build_doc.py
This PR adds a flag in the doc config that will allow users to remove the check that all files are in the TOC. This is not activated by default because we often want to error when a contributor forgets to add a new doc file to the TOC.
> Add option to remove TOC check

- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
`<video xyz></video>` was already working since doc-builder detects opening & closing tags of html. However, when they are combined `<video xyz/>` was not being detected as HTML video tag. This PR solves it
> Escape html vid tag

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- setup.py
- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
- src/doc_builder/external.py
- tests/test_autodoc.py
While adding some reference docs to `timm`'s Docs, I noticed the "Source" links were incorrect in the API documentation - they always pointed to `github.com/huggingface/timm`. We want them to point to `github.com/rwightman/pytorch-image-models`. 
This PR aims to make that happen. 
As of the time of creating this PR, there is an ambiguity between `package` and `package_name`, which still makes links generate incorrectly with `package_name=timm`, as the github repo name should still be `pytorch-image-models`. Will sort out a fix for that...
> Add repo owner to doc source links

- .github/workflows/delete_old_pr_documentations.yml
- scripts/.prettierrc
- scripts/delete-old-prs.ts
Use `@huggingface/hub` to delete old docs, docs older than 1 month. I wanted to do three months but we're going to periodically squash the repo, and docs can be regenrated anyway.
Use Deno to run the script without the need for a `package.json`.
The Github Action will run every day.
> Script to delete old docs

- kit/src/lib/InferenceApi.svelte
Fixes a bug where `curl` button was showing under inference snippet even though no curl snippet was supplied in the doc file
> Don't show [lang] inference snippet if it was not supplied

- README.md
In section Writing source documentation.
> Have fix bit typo README.md

- src/doc_builder/convert_md_to_mdx.py
- tests/data/convert_include_dummy.txt
- tests/test_convert_md_to_mdx.py
Allow markdown files to include other (non-code) files. Useful to ensure minimal duplication across files.
I added a few test cases (copy-pasted and edited from `literalinclude`)
> Add `<include>` block for including non-code files

- kit/preprocess.js
- kit/src/lib/CopyButton.svelte
Fixes issue where the code attribute for `copy-to-clipboard` functionality is interpreted as valid Svelte code, which leads to SSR errors.
> Encode and decode `copy-to-clipboard` functionality using base64

- src/doc_builder/external.py
cc @mishig25 but I know you're off.
Currently the documentation on Transformers latest release is not building because the `objects.inv` on the stable doc of tokenizers is invalid (might be worth rebuilding the doc on tokenizers latest release @ArthurZucker ).
This PR makes us ignore that error (which appears in `zlib.decompress(b"".join(object_lines)).decode().split("\n")`). It could be refined to the actual exception returned by zlib but I don't have time to debug this right now, so going for the quick fix :-)
> Ignore all errors when trying to unpack refs from an external library

- src/doc_builder/commands/push.py
When [upload_version_yml](https://github.com/huggingface/doc-builder/blob/8ad63afbad27c3d1fd400042a92f0f7f88b895d8/src/doc_builder/commands/push.py#L179-L183) flag is on, doc-builder pushes two updates to hf hub: 1. updated _version.yml files 2. zipped doc built artifacts. However, this was causing a concurrency problem as two files were being uploaded same time
Put the two files in a same folder and upload the folder instead of uploading two files separately
> Fix concurrent uploads

- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
Building/previewing the docs for Transformers.js takes >12 minutes on my system and ~15 minutes with GitHub actions:
After investigating further, its due to this line of code, which consumes >99% of build time:
https://github.com/huggingface/doc-builder/blob/c59346e932a62f9edb9bfbb68c6ac8096ee50282/src/doc_builder/convert_md_to_mdx.py#L85-L87
The regex is very strict, and requires that the start and end tag match. However, in practice, this is not necessary at all (and in fact, will break on slightly malformed html tags). A better (and much faster approach) is to just replace the `<` character of any valid start/end tag (regardless of whether they have a matching pair). That is the purpose of this PR.
---
Before:
```bash
Building the MDX files: 100%|██████████| 30/30 [10:35<00:00, …
```
> Optimize html tag replace regex (Fixes #331)

- .github/workflows/upload_pr_documentation.yml
In Optimum we need to use the `pull_request_target` event to be able to access repo secrets to build PR docs. However, PR docs have not been uploaded since this change happened.
This PR adds support for this event type in the `upload_pr_documentation` workflow.
> Add support for the `pull_request_target` event in the `upload_pr_documentation` workflow

- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
Related to https://github.com/huggingface/doc-builder/pull/373 which broke the docs in `huggingface_hub` (see https://github.com/huggingface/doc-builder/pull/373#issuecomment-1697142555). The issue is caused by a [docstring](https://github.com/huggingface/huggingface_hub/blob/111fdbe3508a8727da7acf17ee84ec613608b801/src/huggingface_hub/file_download.py#L1026) in which both a `"<"` and a `">"` are written but not as a HTML tag (e.g.`"... <5MB ....  .... something -> something else"`). This PR fixes it, hopefully without breaking other docs.
In details:
- Update `_re_lt_html`:
- remove `re.DOTALL` (unused in the regex)
- add `re.IGNORECASE`
- update from `\w+` to `[a-z]` after the first `"<"` => the start of a tag must be a letter, not an alphanumeric. This way we don't capture string like …
> FIX html escape regex

- README.md
I think this is right. Setting up doc-builder for RLHF-handbook this time. Cheers.
> Update README.md with missing build command

- README.md
I think all these are missing `build`, eh?
> fix doc builder build cmd in README.md

- .github/workflows/build_pr_documentation.yml
Doesn't change much for existing repo (will still use the main branch) but useful if we want to quickly try a 'doc-builder' PR on another library repo. Should avoid to push a temporary commit like this next time: https://github.com/huggingface/doc-builder/pull/398#issuecomment-1727853754
cc @mishig25 @xenova
> Add `doc_builder_revision` as workflow input to ease debugging

- kit/package-lock.json
- kit/package.json
- kit/preprocess.js
- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
`<` & `{` are special characters in svelte syntax. Therefore, you can't write a doc content like `4<5`. To fix this problem, we were escaping those characters with their respective html codes (`lt;` & `lcub;`) in our python code using regexes. These regexs were slow, which was fixed in #373 and #394. However, there were still [some errors](https://github.com/huggingface/course/actions/runs/6237243960/job/16994401348?pr=614#step:11:70)
Fix it at markdown/mdsvex AST level using a [custom remark plugin](https://mdsvex.com/docs#remarkplugins--rehypeplugins)
[AST Playground](https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/1274c6b594302bbf4e7f9c798504837ae01093e5)
When AST tree is being traversed, if a node type is "text" (rather than "html"), then escape `<` & `{` with `&#60;` …
> Fix svelte special chars escaping problem

- .github/workflows/accelerate_doc.yml
- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Couldn't reproduce [this error](https://github.com/huggingface/huggingface_hub/actions/runs/6295850155/job/17090652777) locally:
```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /tmp/tmp2zqefn3k/kit/src/routes/guides/search/+page.svelte:202:169
200:   let t105;
201:   let p15;
202:   let textContent_20 = `<img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/search_text_classification.gif" alt="Animation exploring `model_args...
```
Locally, I'm running node 20 while the gh workflows were running node 18. Therefore, bumping up the versions to node 20 to see if it solves the issue
cc: @Wauplin
> Node version 18 -> 20

- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
Should fix [the following error](https://github.com/huggingface/huggingface_hub/actions/runs/6295850155/job/17090652777) locally:
```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /tmp/tmp2zqefn3k/kit/src/routes/guides/search/+page.svelte:202:169
200:   let t105;
201:   let p15;
202:   let textContent_20 = `<img src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/search_text_classification.gif" alt="Animation exploring `model_args...
```
as you can see in `let textContent_20 = `, svelte/mdsvex compile is using \`, which is why the alt description can't have \`
> Escape ` inside img alt descriptions

- kit/package-lock.json
- kit/package.json
- kit/preprocess.js
- src/doc_builder/autodoc.py
- src/doc_builder/convert_md_to_mdx.py
- tests/test_autodoc.py
- tests/test_convert_md_to_mdx.py
When there `{` is within a user supplied html string, it was causing svelte compiler error since `{` is a reserved character.
Escape `{` with `&#123;`
Description of steps:
1. When there a html string inside mdsvex files, marked AST parses the outer most tag without without further parsing. For example, `<div><p>test</p></div>` will be parsed as single node without children. [AST playground](https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/62221cb9b1e5f555f3752553572e4abb296dd1a4)
2. Therefore, when there is a html node, parse it further with [cheerio](https://cheerio.js.org/docs/intro) and replace `{` with `&#123;` within texts
3. Problem solved
Should fix https://github.com/xenova/transformers.js/actions/runs/6300637437/job/17103917897?pr=320
todos:
> Escape { in user supplied html

- README.md
Fixes the auto-generated toctree hashlinks in readme
> Fix readme toctree links

- kit/svelte.config.js
Page https://huggingface.co/docs/trl/v0.7.1/en/ddpo_trainer was [failing](https://github.com/huggingface/trl/actions/runs/6316410973/job/17169856790) with:
```
node:internal/event_target:1083
process.nextTick(() => { throw err; });
^
Error: 500 /docs/trl/main/en/ddpo_trainer
```
Setting `sveltekit.prerender.handleHttpError` option from `fail` to `warn` solves the issue. Need a better fix. I'm not exactly sure why this error is happening at the moment. Tested the new builds locally to make sure of correctness.
> [Fix] trl doc build

- kit/preprocess.js
- kit/src/lib/DropdownEntry.svelte
- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
With https://github.com/huggingface/doc-builder/pull/401, we are escaping `{` so that it gets treated as string rather than inline svelte js. However, that caused line below to get treated as literal string rather than js https://github.com/huggingface/doc-builder/blob/787f9afb98805dbce39f8e5ae59c175fee104daf/kit/src/lib/DropdownEntry.svelte#L40
Escape `{`, `<` only in user written markdown doc. Don't escape for [svelte components](https://github.com/huggingface/doc-builder/tree/main/kit/src/lib) (i.e. treat `{` as regular svelte inline js)
> Escpaing of svelte characters inside doc body only

- kit/preprocess.js
- kit/svelte.config.js
This PR:
1. Reverts changes in https://github.com/huggingface/doc-builder/pull/416. As written in the comment [here](https://github.com/huggingface/doc-builder/pull/416#issuecomment-1739002796), my initial assumption of sveltekit http error 500 being not critical was wrong
2. Escape HTML heading node correctly
```
<h3 id="id">My heading</h3>
Some markdown paragraph
```
get interpreted as one big html node by marked (see AST [here](https://astexplorer.net/#/gist/9e50bf2c3e282f02687d66eb1d80bd5a/8c57fd832328284fc405e955432a6cbfc19c28b5)). We would need space between them (see [here](https://github.com/huggingface/doc-builder/pull/419/commits/e6e2083125af846ad11e7c0f17fcce5a33fe5e9d#diff-15664fa10638c7e348d5f6f87bec05dde2e095d76b27797481462687c6a6dab3)).
Below is how it should look like
``` …
```
> [Fix] parsing html node ending correctly

- kit/preprocess.js
- kit/src/lib/CodeBlock.svelte
- kit/src/lib/CodeBlockFw.svelte
If you want to wrap your code blocks in a file, you need to put this html comment `` which acts as a flag
feature was requested by @Narsil for making long CLI options more readable https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher
> [Feature] Option to wrap code blocks

- kit/src/lib/CodeBlock.svelte
- kit/src/lib/CodeBlockFw.svelte
Follow up to #420 
[whitespace-normal](https://tailwindcss.com/docs/whitespace#normal) (before)
[whitespace-pre-wrap](https://tailwindcss.com/docs/whitespace#pre-wrap) (this PR)
> Use `whitespace-pre-wrap` for wrapping code blocks

- kit/preprocess.js
Fix json stringify escaping
You can see the error here https://github.com/huggingface/datasets/actions/runs/6498370197/job/17649557908
> Fix json stringify escaping

- src/doc_builder/external.py
Follow up to https://github.com/huggingface/doc-builder/issues/258
Support trl objects in docs intralinking
cc: @lvwerra
> Rm package name check when intralinking

- kit/preprocessors/hfOptions.js
- kit/preprocessors/index.js
- kit/preprocessors/utils.js
- kit/src/lib/HfOption.svelte
- kit/src/lib/HfOptions.svelte
- kit/src/lib/stores.ts
- kit/src/lib/utils.ts
- kit/svelte.config.js
- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
New syntax to add different options.
```html
<hfoptions id="id for this entire block">
<hfoption id="id for option 1">
option 1 content markdown
</hfoption>
<hfoption id="id for option 2">
option 2 content markdown
</hfoption>
...
there can be however many options
...
</hfoptions>
```
Syntax example:
cc: @stevhliu
> [New syntax] Hf Options

- setup.py
Add `black` as dependency at install.
Note that, besides `make quality`, `black` is also used in `style_doc.py`: https://github.com/huggingface/doc-builder/blob/e00174632acfddbf3da975dffca90a87aa334f55/src/doc_builder/style_doc.py#L21
> Add black as dependency at install

- setup.py
`requests` is imported here: [src/doc_builder/external.py#L22](https://github.com/huggingface/doc-builder/blob/c4e348ea1c844d659c65261d914e9cb9237a84e3/src/doc_builder/external.py#L22)
> Add `requests` test dependency

- .github/workflows/upload_pr_documentation.yml
Disable upload_pr_documentation.yml until a security issue is fixed
cc: @Michellehbn @coyotte508
> Disable upload_pr_documentation.yml

- .github/workflows/upload_pr_documentation.yml
Use `echo >> GITHUB_OUTPUT` rather than `echo >> GITHUB_ENV` because the lines below were previously security vulnerability with `echo >> GITHUB_ENV` (see hackerrank one)
https://github.com/huggingface/doc-builder/blob/c33e00834df8e85b18cdefccd56e26acb53a5be0/.github/workflows/upload_pr_documentation.yml#L75-L81
Unlikes `GITHUB_ENV`, `GITHUB_OUTPUT` gets sanitized
> Use GITHUB_OUTPUTS, not GITHUB_ENV for security reasons

- .github/workflows/upload_pr_documentation.yml
In Optimum, we sometimes need to trigger the PR doc build manually: when modifying the [PR doc build workflow](https://github.com/huggingface/optimum/blob/main/.github/workflows/build_pr_documentation.yml) in a PR, the only way to execute the PR version of this workflow (and not the one from `main`) is with a `workflow_dispatch` event. This happens because we use the `pull_request_target` event to be able to access secrets during doc generation.
This PR adds the `workflow_dispatch` event as a compatible event for the doc upload workflow.
> Add `workflow_dispatch` to events that trigger upload PR doc

- README.md
- kit/preprocessors/mdsvex/index.js
Markdown below
```md
> [!TIP]
> Here is a tip. Go to this url [website](www.tip.com)
> 
> Second line
> [!WARNING]
> Here is a warning. Go to this url [website](www.warning.com)
> 
> Second line
> Just a regular blockquote
> 
> Second line
```
gets rendered as 
See https://github.com/orgs/community/discussions/16925 for the information
> use github-like Tip & Warning syntax

- src/doc_builder/commands/notebook_to_mdx.py
in `notebook_to_mdx ` cmd, when `output_dir` is not specified, `output_dir` should be parent dir of the noteboom file that is being converted
> [Fix] notebook_to_mdx command corerct output dir

- setup.py
Adds release directions to the setup.py to mimic the rest of our O.S. libraries
> Add release directions + license to setup.py

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
This PR adds a new options `custom_container` to build PR in the CI in a custom container. By default, workflow runs inside `"huggingface/transformers-doc-builder"` which is the container needed for `transformers` and that has all dependencies like torch, tensorflow, etc. However, it takes quite some time (>2min) to initialize the container in the CI given its size. In theory, most libraries don't need this container so we should be able to bypass this step and run directly on `ubuntu:latest`. 
This PR is related to https://github.com/huggingface/huggingface_hub/pull/2140 in which I tested the idea.
---
[As discussed on slack](https://huggingface.slack.com/archives/C04F8N7FQNL/p1711384899462349?thread_ts=1711041424.720769&cid=C04F8N7FQNL) (internal), plan is:
1. we merge …
> Test build pr outside container

- setup.py
- src/doc_builder/commands/notebook_to_mdx.py
Follow up to https://github.com/huggingface/doc-builder/pull/492
There was svelte parser error when the image output was `png`. Therefore, converting `png` output to `jpeg` before creating svelte/html img element
> [fix] ntoebook png image output

- src/doc_builder/build_doc.py
Fixes an issue reported by @NielsRogge 
> Hi, when clicking on "generate()" (the PyTorch one) here: https://huggingface.co/docs/transformers/en/main_classes/text_generation, it links to https://huggingface.co/docs/transformers/v4.38.2/en/model_doc/phi#transformers.PhiForCausalLM.generate, for some reason. It should normally link to https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationMixin.generate.
The code is defined correctly: https://github.com/huggingface/transformers/blob/main/docs/source/en/main_classes/text_generation.md
> [fix] overwrite defined python object link

- kit/src/lib/EditOnGithub.svelte
- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
Now on the bottom of every page, there is a btn to update the page source on github
> Update on Github btn

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Fix bug introduced in https://github.com/huggingface/doc-builder/pull/488.
Problem comes from that the venv is not properly activated in some cases. See failed CI in [computer vision course](https://github.com/johko/computer-vision-course): https://github.com/johko/computer-vision-course/actions/runs/8895303169/job/24425352840. This PR should fix it.
cc @mishig25 @coyotte508 @merveenoyan
> Fix venv not sourced when pushing docs

- .github/workflows/accelerate_doc.yml
- kit/preprocessors/hashInCode.js
- kit/preprocessors/index.js
- kit/preprocessors/mdsvex/index.js
- kit/preprocessors/utils.js
- kit/svelte.config.js
Escape `#` char inside code/codeblocks into its html5 entity `&amp;num;`. Otherwise, an extra new space was being rendered. Discovered after checking the renderings from https://github.com/huggingface/chat-ui/pull/1155
| main    | this branch/pr |
| -------- | ------- |
| ![image](https://github.com/huggingface/doc-builder/assets/11827707/630ff31e-3758-41b7-886b-0311604278d4)  | ![image](https://github.com/huggingface/doc-builder/assets/11827707/7422b91e-415c-453c-b087-5922210862fb)   |
> Escape hash in code/codeblocks

- .github/workflows/accelerate_doc.yml
- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_old_pr_documentations.yml
- .github/workflows/lint-svelte-kit.yml
- .github/workflows/quality.yml
- .github/workflows/test.yml
- .github/workflows/upload_pr_documentation.yml
Currently, we get deprecation warnings when building our docs: https://github.com/huggingface/datasets/actions/runs/9547896244
```
build / build_main_documentation
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
This PR updates the required GitHub Actions to use Node 20.
> Update GitHub Actions to use Node 20

- .github/workflows/accelerate_doc.yml
- .github/workflows/build_pr_documentation.yml
In hf docs github CI, we are facing a same issue described [here](https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana).
> Use python virtual env for gh CI

- .github/workflows/accelerate_doc.yml
- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- .github/workflows/upload_pr_documentation.yml
Follow up to #528 #529 #530
`ubuntu-latest` is now `ubuntu-24.04` and it is breaking stuff.
#528 #529 #530 handled `uv` install error described [here](https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana).
However, more errors are happening. Such as:
> python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found
Therefore, for now, pinning `ubuntu-22.04`
> Pin ubuntu-22.04 for build_pr_documentation.yml

- .github/workflows/quality.yml
- .github/workflows/test.yml
- src/doc_builder/autodoc.py
- tests/test_autodoc.py
should fix the CI
Sets python3.10 as Python version in CI
This PR also simplifies `get_type_name` logic. From 3.9 onwards, `typing` resolves types by itself in a much cleaver way than before. Typically, `typing.Optional[Union[str, None]]]` is automatically converted to `typing.Optional[str]`. So let's use this instead of a custom regex. I've added a test to confirm everything works as before. `get_type_name` is now trivial but let's keep it so that it can be tested independently.
> Update python version in CI

- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
(testing things for timm)
Explanation:
1. docstring is parsed => parameters section is located from the `Args:` (or `Parameters:`) title
2. then, each arg section is detected. The logic detect new args from the indentation. The first line of an arg looks like this:
```
filter_bias_and_bn (*str*, _optional_):  If True, bias, norm layer parameters (...)
```
3. then, the arg first line is reformatted to
```
- **filter_bias_and_bn** (*str*, _optional_) -- If True, bias, norm layer parameters (...)
```
=> a regex splits the line around `":"`
=> another regex detects the arg name "`filter_bias_and_bn`" and adds the `** **` around it
=> finally, a string concatenation is applied to replace the `:` by a `--`
**This is the step that got modified in this PR.**
4. Later in the process, if an arg …
> Fix args parsing when argument doesn't have a type

- .github/workflows/build_pr_documentation.yml
`actions/upload-artifact@v3` is no longer working, see e.g. [this workflow](https://github.com/huggingface/transformers/actions/runs/12813495878/job/35727693015?pr=35709)
> bump `actions/upload-artifact` version

- .github/workflows/upload_pr_documentation.yml
`actions/upload-artifact@v3` recently had to be upgraded because it is now deprecated (see https://github.com/huggingface/doc-builder/pull/541).
However, the logic used to download the uploaded artifact does not work anymore with this upgrade. This PR fixes this issue and replaces the custom download logic with `actions/download-artifact@v4`.
> Fix PR doc upload workflow

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Fix for doc builder failure due to lack of disk space in `transformers`, e.g. https://github.com/huggingface/transformers/actions/runs/13968457454/job/39104194581?pr=36850
> [CI] update PR doc builder machine

- kit/src/lib/InferenceSnippet/InferenceSnippet.svelte
Makes the href work on local setup + on PR docs
> Absolute URL in InferenceSnippets tooltip

- kit/package-lock.json
- kit/package.json
- kit/src/lib/InferenceSnippet/InferenceSnippet.svelte
Following-up on recent breaking change introduced in https://github.com/huggingface/huggingface.js/pull/1347#discussion_r2044512924. `getInferenceSnippets` now takes a `inferenceProviderMapping?: InferenceProviderModelMapping,` instead of `providerModelId?: string,` previously. Nothing else changes in the generated snippets though.
> Bump infererence.js + adapt code

- .github/workflows/accelerate_doc.yml
- .github/workflows/build_embeddings.yml
- setup.py
- src/doc_builder/__init__.py
- src/doc_builder/autodoc.py
- src/doc_builder/build_embeddings.py
- src/doc_builder/commands/embeddings.py
- src/doc_builder/meilisearch_helper.py
- src/doc_builder/utils.py
Usage of the new command:
```
doc-builder embeddings [lib name] [docs path]
```
1. **Step 1:** Create chunks from docs files
```ts
interface Chunk {
text: string, // "# Effective and efficient diffusion\nGetting the `DiffusionPipeline` to generate images in a certain style or include what you want can be tricky ...
source: string, // source url ex: hf.co/docs/transformers/model_doc/bert#transformers.BertConfig
package_name: string, // ex: transformers, diffusers
}
```
doc-builder handles all the [autodoc derivatives](https://github.com/huggingface/transformers/blob/14ff5dd962c1bd0a4e3adaac347ba396d8df5add/docs/source/en/model_doc/bert.md?plain=1#L190) to crawl correct python objects and get their docstrings in markdowns. For example, find diffusers chunks at …
> Build embeddings

- src/doc_builder/build_doc.py
Support building notebooks from .md files.
Currently, to have notebooks built, we need to set the `.mdx` extension in our docs. This impacts rendering in GitHub and IDEs.
> Support building notebooks from .md files
