huggingface/doc-builder

- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_md_to_mdx.py
ColabDropdown needs to be a svelte component
https://user-images.githubusercontent.com/11827707/145053749-6efbaf22-b11b-4887-8767-92521fe8174c.mov
> Add colabdropdown svelte import

- build/transformers/master/en/preprocessing.mdx
- build/transformers/master/en/quicktour.mdx
- build/transformers/master/en/tokenizer_summary.mdx
- build/transformers/master/en/training.mdx
- build/transformers/v4.13.0/en/preprocessing.mdx
- build/transformers/v4.13.0/en/quicktour.mdx
- build/transformers/v4.13.0/en/tokenizer_summary.mdx
- build/transformers/v4.13.0/en/training.mdx
Manually fixing it so that the changes are up ASAP.
Will work on changing the code
cc: @sgugger @LysandreJik
> Manual fix youtube

- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_md_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Fixes error where <YouTube becomes alt;ltYoutube
> Unescape <YouTube

- src/doc_builder/commands/convert_doc_file.py
This PR makes some improvement to the `doc-builder convert` command, to simplify all references likes [`~transformers.Trainer`] into just [`Trainer`].
> Shorten ref links when converting a doc file

- .github/workflows/test.yml
- src/doc_builder/autodoc.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_autodoc.py
- tests/test_convert_rst_to_mdx.py
This PR adds a few fixes for the docstring conversion from rst to Markdown, and fixes one of the test due to the docstring changing on the Transformers side.
This is rather urgent so merging now and will address potential comments in a future PR :-)
> Fixes to the conversion

- kit/README.md
- kit/package-lock.json
- kit/package.json
- kit/src/app.html
- kit/src/routes/__layout.svelte
- kit/src/routes/endpoints/toc.ts
Fix #97 
Inside the `kit` folder, do `npm run dev`. 
Then go to http://localhost:3000/docs/transformers/master/en :  
This allows users to easily switch between doc files with a basic sidebar
> Preview doc in dev mode

- src/doc_builder/autodoc.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_rst_to_mdx.py
Catch `yields` section in docstrings
> Catch docstring yields

- kit/svelte.config.js
Just like in [here](https://github.com/huggingface/moon-landing/blob/4a16818bf77260ad9f3d23d530c990b859fac464/server/build-svelte.mjs#L164-L166)
> Suppress noisy warnings

- kit/svelte.config.js
- src/doc_builder/commands/build.py
For https://github.com/huggingface/transformers/pull/15710
> Log node errors

- kit/src/lib/CodeBlock.svelte
- kit/src/lib/CopyButton.svelte
| Before                                                                                                                                                                | After                                                                                                                                                                 |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="448" alt="Screenshot 2022-03-01 at 11 49 44" src="https://user-images.githubusercontent.com/11827707/156156596 …
> Fix copy btn bug

- .github/workflows/test.yml
- src/doc_builder/__init__.py
- src/doc_builder/commands/doc_builder_cli.py
- src/doc_builder/commands/style.py
- src/doc_builder/convert_to_notebook.py
- src/doc_builder/style_doc.py
- tests/test_style_doc.py
This PR ports the doc-styler util we use in Transformers to this repo and adds tests for it.
> Add doc styling util

- src/doc_builder/commands/build.py
- src/doc_builder/utils.py
- tests/test_utils.py
#134 needed to be merged quickly. This PR takes the time to clean up things a bit and use a better check for the main branch name.
> Cleanup default branch check

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
This PR adds templates for the jobs that:
- build the doc at each commit on master
- build the doc for each PR
- clean the doc after each PR
The last two have been tested on Accelerate. The first one still needs testing.
> Adds templates for doc building workflows

- src/doc_builder/commands/build.py
This adds the ability to customize the version prefix via the doc config.
> Add ability to customize version prefix

- tests/test_autodoc.py
There is this annoying guy sgugger that keeps making changes in the docstrings of Transformers we test here. This PR should fix the tests.
> Fix tests for latest Transformers

- src/doc_builder/autodoc.py
- src/doc_builder/build_doc.py
- src/doc_builder/commands/build.py
Closes #189
Creating a new variable `version_tag` (I think it is the simplest solution)
> Fix dstasets version `v` tag issue

- src/doc_builder/commands/build.py
Hotfix to [this problem](https://huggingface.slack.com/archives/C027NLU6CE9/p1651056613127479)
Thanks a lot[ for the suggestion](https://github.com/huggingface/doc-builder/pull/202#discussion_r859696270), @sgugger !
(merging them so that I can fix the broken links in the prod 😊)
> Hotfix version issue

- kit/postbuild.sh
Fix "Rm [hash] from doc-build artifcats (#218)"
> Fix "Rm [hash] from doc-build artifcats (#218)"

- .github/workflows/build_pr_documentation.yml
Reverts huggingface/doc-builder#221
> Revert "Comment bot use correct package name"

- src/doc_builder/commands/push.py
See more [here](https://huggingface.slack.com/archives/C02GLJ5S0E9/p1653480092835589)
> Sleep 5 seconds before retry push graphql

- src/doc_builder/commands/push.py
Should fix error from [this gh action](https://github.com/huggingface/transformers/runs/6594584291?check_suite_focus=true) by creating graphql client per request:
```
createCommitOnBranch error occurred: [Errno 104] Connection reset by peer
```
> Create new graphql Client per request

- .github/workflows/build_main_documentation.yml
Fixes https://github.com/huggingface/hub-docs/runs/6690618047?check_suite_focus=true
> Fix build main doc yml

- src/doc_builder/commands/push.py
Use `with` syntax with `GraphQLClient` to use https://github.com/graphql-python/gql/blob/master/gql/client.py#L619-L645 
trying to fix doc-build error in: https://github.com/huggingface/transformers/pull/17313#issuecomment-1150841943
cc: @sgugger @NielsRogge
> Use `with` syntax with `GraphQLClient`

- src/doc_builder/commands/build.py
- src/doc_builder/commands/preview.py
> Refactor svelte build env vars

- kit/preprocess.js
Fixes https://huggingface.slack.com/archives/C02GLJ5S0E9/p1655488551480829
Read more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline)
> Need to add multiline flag to REGEX_CODE_INPUT

- kit/preprocess.js
Fixes https://huggingface.slack.com/archives/C02GLJ5S0E9/p1657129417293849
cc: @sgugger
> Fix copy code regex match

- kit/preprocess.js
Was mentioned [here](https://github.com/huggingface/doc-builder/issues/266#issuecomment-1198994214)
> Do NOT render undefined `desciripon` inside changed directive

- kit/preprocess.js
Update docstring directive regex to detect:
```
<Added version="2.4.0" />
```
(empty space before closing tag `/>`)
> Fix directive regex inside docstring

- src/doc_builder/commands/push.py
This reverts commit d3856a59914c87fbabce74b40e84829cbdc47d14. because of https://github.com/huggingface/doc-builder/issues/275
In the meantime, will work on a fix
> Revert "`create_commit` cmd support deletions (#274)"

- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
Adds private token management even for private repositories
> Private token management even for private repositories

- kit/src/lib/CourseFloatingBanner.svelte
- kit/src/lib/DocNotebookDropdown.svelte
- src/doc_builder/convert_md_to_mdx.py
- src/doc_builder/convert_rst_to_mdx.py
- tests/test_convert_md_to_mdx.py
Needed for https://github.com/huggingface/course/issues/248
Adds a "ask a question" floating banner next to notebooks on course pages
> Add CourseFloatingBanner.svelte

- kit/src/lib/DocNotebookDropdown.svelte
> DocNotebook.svvelte stricter length check

- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/push.py
Reverts huggingface/doc-builder#283
> Revert "Add `create_deletions` cmd"

- .github/workflows/delete_doc_comment.yml
- src/doc_builder/commands/push.py
Delete PR docs using GraphQL (through github action)
> Delete PR docs using GraphQL

- .github/workflows/delete_doc_comment.yml
> Add `doc-builder` CLI to delete_doc.yml

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Reverts huggingface/doc-builder#302
> Revert "Add repo_owner input to build workflows"

- .github/workflows/build_main_documentation.yml
Follow up to https://github.com/huggingface/doc-builder/pull/309
> Fix github main action

- kit/postbuild.sh
Closes https://github.com/huggingface/doc-builder/issues/319
> Keep `_redirects.yml` in doc build artifacts

- .github/workflows/build_pr_documentation.yml
- .github/workflows/delete_doc_comment.yml
tested at: https://github.com/huggingface/accelerate/pull/863
> Fix doc comment duplication

- .github/workflows/build_main_documentation.yml
> Fix notebooks push

- README.md
Hey there 👋 ,
I just added to the documentation that preview does work with windows.
Also modified the documentation of course: https://github.com/huggingface/course/pull/389
> Update documentation to mention that preview does not work with windows

- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/push.py
Fix #340. Reasoning: much easier / faster to browse https://huggingface.co/datasets/hf-doc-build/doc-build-dev.
Tried for the dev doc in https://github.com/huggingface/hub-docs/pull/637, it works, generated those commits:
- https://huggingface.co/datasets/hf-doc-build/doc-build-dev/commit/249cace06cac547b445e5a0ee3af13a85a337f05
- https://huggingface.co/datasets/hf-doc-build/doc-build-dev/commit/d4d7870f89e2f9529e28fcc4ad7b27e1c7af42a2
Will need to migrate existing files once merged, also, a lot of zip files from past PRs seem to be present, can take the opportunity to clean them up
> 🚚 Upload to lib/version.zip instead of lib@@@version.zip

- src/doc_builder/commands/push.py
https://huggingface.slack.com/archives/C02GLJ5S0E9/p1675471691097609
Repos are migrated, we can remove the migration code!
Follow up to https://github.com/huggingface/doc-builder/pull/344
> ⏪ Remove migration code + legacy separator

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- Makefile
- README.md
- kit/package-lock.json
- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
> Upgrade node + Fix <source> sanitization

- src/doc_builder/convert_to_notebook.py
- tests/test_convert_to_notebook.py
This PR fixes #358 and it'll allow the Diffusers docs to build Jax notebooks! 🎉
> Add support for building Jax notebooks

- kit/svelte.config.js
> 🐛 Fix "Cannot load tranformers/module"

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Fix #360 
Slack: https://huggingface.slack.com/archives/C04U1CZQBQX/p1682775421137039 cc @xenova (hopefully it'll fix)
> 👷 Add pre_command input to CI job

- kit/preprocess.js
- kit/src/lib/Docstring.svelte
- kit/src/lib/ExampleCodeBlock.svelte
- kit/tailwind.config.cjs
Companion PR to https://github.com/huggingface/hub-docs/pull/799
> Fix hover css

- kit/preprocess.js
- kit/src/lib/Docstring.svelte
- kit/src/lib/ExampleCodeBlock.svelte
follow up to https://github.com/huggingface/doc-builder/pull/380
> Fix more hover css

- .github/workflows/quality.yml
- .github/workflows/test.yml
- setup.py
Update python version of workflow files since transformers no longer support python 3.7 https://github.com/huggingface/transformers/pull/24091
> Update python version of workflow files

- kit/preprocess.js
Should fix this doc-build error https://github.com/huggingface/diffusers/actions/runs/6291559822/job/17080928570
> Fix inline code escaping

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
As far as I understand these environment variables will then apply to all tests, but they really only matter for the diffusers tests as the name is very diffusers specific
> [Diffusers] Set import to slow as env variable

- README.md
> [Doc readme] Document Code Block Wrap flag

- kit/src/lib/HfOptions.svelte
- kit/src/lib/InferenceApi.svelte
- kit/src/lib/TokenizersLanguageContent.svelte
- kit/src/lib/utils.ts
> URL replaceState rather than pushState

- README.md
Document https://github.com/huggingface/doc-builder/pull/431
> Document HF Options syntax

- kit/src/routes/+layout.svelte
Reverts huggingface/doc-builder#440
> Revert "[Docs partial load] Handle on default paths"

- src/doc_builder/convert_md_to_mdx.py
- tests/test_convert_md_to_mdx.py
Reverts huggingface/doc-builder#439
> Revert "Expose sveltekit goto function to window"

- kit/package-lock.json
Run `npm audit fix` to fix suggested
```
4 vulnerabilities (2 low, 1 moderate, 1 high)
```
> Run `npm audit fix`

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- setup.py
- src/doc_builder/commands/notebook_to_mdx.py
Extend functionalities to #263
> Better support for notebooks-to-md

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/notebook_to_mdx.py
> [Feature] add colab link to automaitc nb -> md conversion

- kit/src/lib/DocNotebookDropdown.svelte
> [Lint] sveltekit

- setup.py
- src/doc_builder/__init__.py
W/ the release, don't have push-to-main permissions
> Update init version

- src/doc_builder/build_doc.py
This feature allows a file named `abc` to be published in new url/local such as `hf.co/docs/library/xyz` rather than `hf.co/docs/library/abc`. The toctree should look like this:
```yml
title: Chapter Abc
local: abc
newlocal: xyz # this is the new field this PR is using
```
In most cases, if you can, you should  just rename the file `abc` to `xyz` rather than using `newlocal` inside toctree
> [toctree] support renaming `local`

- src/doc_builder/commands/notebook_to_mdx.py
Notebook-to-mdx script should render notebook img outputs as html `<img>` elements
> [notebook conversion] render img outputs

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
1. **CI will now run by default on the main runner** instead of custom container. For now the only repo specifically running inside the custom container is `transformers` (see https://github.com/huggingface/transformers/pull/29855 - already merged). From my tests, it is the only repo that needs it.
2. **When running on the base runner** (i.e. all repos except `transformers`):
1. `uv` is used to install dependencies. It's much faster and works correctly. It requires to run inside a virtualenv but that's fine.
2. `sudo apt-get` is used to install packages
5. **When running in a custom container** (i.e. only `transformers`):
1. we continue to use `pip` which is faster since all packages have already been installed/cached when building the container. `uv` would be less optimal in this case. …
> Test install deps with uv

- kit/preprocessors/hashInCode.js
Follow up to https://github.com/huggingface/doc-builder/pull/504
> Fix REGEX_INLINE_CODE for escaping # in inline codes

- .github/workflows/delete_old_pr_documentations.yml
- scripts/delete-old-prs.ts
cc @Hugoch this will clear up a lot of old files once merged (all files older than 1 month)
It was stuck before because of an API change
> Log more info in delete-old-doc + actually delete old files

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
cc: @xenova so that you can use to build transforerms.js v3 versioned docs
> Add `version` input in github actions

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
- src/doc_builder/commands/build.py
This reverts commit 9b360347a92fb83f555f9e823a4b4e12efbbdb91.
> Revert "Add `version` input in github actions (#517)"

- .github/workflows/build_pr_documentation.yml
Update actions/upload-artifact from v3 to v4
Fix #520.
> Update actions/upload-artifact from v3 to v4

- .github/workflows/build_pr_documentation.yml
Reverts huggingface/doc-builder#521
> Revert "Update actions/upload-artifact from v3 to v4"

- .github/workflows/upload_pr_documentation.yml
Reverts huggingface/doc-builder#522
> Revert "Upgrade to actions/github-script@v7"

- src/doc_builder/autodoc.py
> fix `find_object_in_package`

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
> pip install -U uv --break-system-packages

- .github/workflows/upload_pr_documentation.yml
> Add `--break-system-packages` to pip commands to fix doc uploads

- .github/workflows/upload_pr_documentation.yml
> Set `upload_pr_documentation` to run on ubuntu-22.04

- .github/workflows/build_main_documentation.yml
See https://huggingface.slack.com/archives/C1RCG46LS/p1729118325934509?thread_ts=1728616969.079469&cid=C1RCG46LS.
> Pin ubuntu-22.04 in the build_main_documentation workflow

- README.md
> Fix internal link syntax

- .github/workflows/build_main_documentation.yml
- .github/workflows/build_pr_documentation.yml
Reverts #546 
A better fix is being worked on #547
> revert 546

- kit/package-lock.json
- kit/package.json
- kit/src/lib/InferenceSnippet/InferenceSnippet.svelte
this should fix https://github.com/huggingface/hub-docs/actions/runs/15041158143/job/42272993169?pr=1726
> bump `huggingface.js` packages

- setup.py
chore: remove specific version reference for huggingface_hub in setup.py
> chore: remove specific version reference for huggingface_hub in setup.py

- kit/package-lock.json
- kit/package.json
This PR updates:
- `@huggingface/tasks`
- `@huggingface/inference`
It was generated automatically by the [Bump huggingface.js packages workflow](https://github.com/huggingface/huggingface_hub/blob/main/.github/workflows/bump-huggingface-js-packages.yml).
Please verify and merge if all looks good.
Ping: @Wauplin @mishig25
> [Bot] Bump huggingface.js packages

- .github/workflows/build_embeddings.yml
- src/doc_builder/build_embeddings.py
- src/doc_builder/commands/embeddings.py
Add gradio docs to semantic search
> Add gradio docs to meilisearch

- .github/workflows/build_pr_documentation.yml
Let's avoid issue by only running checkout if event is issue_comment
> fix checkout specific commit

- kit/src/app.css
- kit/src/lib/Tip.svelte
Follow up to https://github.com/huggingface/doc-builder/pull/632
> Refactor course-tip styles and update Tip component to use blockquote for better semantic structure
